session_name: oh-my-vim
start_directory: ./
windows:
  - panes:
      - null
  - panes:
      - null
  - panes:
      - null
  - panes:
      - null
  - panes:
      - null
  - panes:
      - null
  - panes:
      - null
  - panes:
      - null
  - window_name: git pull
    start_directory: ~/.config/nvim
    panes:
      - while true; do git pull; sleep 1; done;
